return {
  "folke/todo-comments.nvim",
  event = { "BufReadPre", "BufNewFile" },
  keys = { { "tt", "<cmd>TodoTelescope<cr>" } },
  opts = {
    signs = true,
    sign_priority = 10,
    keywords = {
      FIX = {
        icon = " ",
        color = "error",
        alt = { "FIXME", "BUG", "FIXIT", "ISSUE", "fix", "fixme", "bug", "fixit", "issue" },
        signs = true,
      },
      TODO = { icon = " ", color = "info", alt = { "todo" } },
      HACK = { icon = " ", color = "warning", alt = { "hack" } },
      WARN = { icon = " ", color = "warning", alt = { "WARNING", "XXX", "warning", "xxx", "warn" } },
      PERF = {
        icon = " ",
        alt = { "OPTIM", "PERFORMANCE", "OPTIMIZE", "optim", "performance", "optimize", "perf" },
      },
      NOTE = { icon = " ", color = "hint", alt = { "INFO", "info", "note" } },
      TEST = {
        icon = "☆ ",
        color = "test",
        alt = { "TESTING", "PASSED", "FAILED", "testing", "passed", "failed", "test" },
      },
    },
    gui_style = {
      fg = "NONE",
      bg = "BOLD",
    },
    merge_keywords = true,
    highlight = {
      multiline = true,
      multiline_pattern = "^.",
      multiline_context = 10,
      before = "",
      keyword = "wide",
      after = "fg",
      pattern = [[.*<(KEYWORDS)\s*:]],
      comments_only = true,
      max_line_len = 400,
      exclude = {},
    },
    colors = {
      error = { "DiagnosticError", "ErrorMsg", "#DC2626" },
      warning = { "DiagnosticWarn", "WarningMsg", "#FBBF24" },
      info = { "DiagnosticInfo", "#2563EB" },
      hint = { "DiagnosticHint", "#10B981" },
      default = { "Identifier", "#7C3AED" },
      test = { "Identifier", "#FF00FF" },
    },
    search = {
      command = "rg",
      args = {
        "--color=never",
        "--no-heading",
        "--with-filename",
        "--line-number",
        "--column",
      },
      pattern = [[\b(KEYWORDS):]],
    },
  },
}
